spring:
  application:
    name: eureka-ribbon-client
server:
  port: 8769
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
stores:
    ribbon:
       listOfServers: exarnple.com  , google.com
ribbon:
  eureka:
     enabled: false