spring:
  datasource:
    url: jdbc:mysql://47.99.246.142:3306/user?characterEncoding=utf8
    username: root
    password: Liu:123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port:  8089