eureka:
  client:
    serviceUrl:
       defaultZone: http://127.0.0.1:8761/eureka/
  instance:
     preferIpAddress: true

server:
  port: 8675
spring:
  application:
    name: eureka-feign-client
feign:
    hystrix:
       enabled: true